# cibuildwheel configuration for pyreadstat
# This file configures how cibuildwheel builds wheels for this project

[build]
# Python versions to build for (matching config.toml)
python-versions = ["3.12"]

# Skip Python versions that are no longer supported
skip = [
    "cp27-*", "pp27-*",  # Python 2.7
    "cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp313-*", "cp314-*",  # Skip Python 3.8-3.11, 3.13-3.14, only build 3.12
    "pp36-*", "pp37-*", "pp38-*", "pp39-*", "pp310-*", "pp311-*", "pp312-*", "pp313-*",  # PyPy
]

# Build configurations for different platforms
[build.archs]
# Build for x86_64 only on Linux (for faster testing)
linux = ["x86_64"]
# Build for x86_64 and arm64 on macOS
#macos = ["x86_64", "arm64"]
# Build for x86_64 on Windows
#windows = ["x86_64"]

# Environment variables for the build
[build.environment]
# Set build verbosity
CIBW_BUILD_VERBOSITY = "1"
# Use auto platform detection
CIBW_PLATFORM = "auto"
# Use auto architecture detection
CIBW_ARCHS = "auto"

# Before build commands
[build.before-build]
# Install system dependencies for Linux
linux = """
sudo apt-get update
sudo apt-get install -y build-essential
"""
# Install system dependencies for macOS
macos = """
# macOS dependencies are typically handled by cibuildwheel
"""
# Install system dependencies for Windows
windows = """
# Windows dependencies are typically handled by cibuildwheel
"""
[tool.cibuildwheel]
test-sources = ["pyreadstat/tests", "requirements_test.txt"]
test-requires = ["pandas", "narwhals==2.0.1"]
test-command = "python pyreadstat/tests/test_basic.py"

# Test commands to run after building
#[build.test-command]
# Basic import test
#command = "python pyreadstat/tests/test_basic.py"

# Test dependencies
#[build.test-requires]
# Add test dependencies
#packages = ["pytest>=6.0", "pandas>=1.0.0", "numpy>=1.16.0"]

# Test extras
#[build.test-extras]
# Install test dependencies
#extras = ["test"]
