name: Build wheels

env:
  # A commit hash for the repo, for which to build wheels. 
  SOURCE_REF_TO_BUILD: ebfb3fa57d071c68402979810a6925219468466c

on: [push]

jobs:
  build_wheels:
    name: Build wheel ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          - [ubuntu-22.04, manylinux_x86_64, ""]

        python: ["cp312"]

    steps:
      - name: Checkout pyreadstat-wheels
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Checkout pyreadstat
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: Roche/pyreadstat
          ref: ${{ env.SOURCE_REF_TO_BUILD }}
          path: pyreadstat
          submodules: true
          persist-credentials: false

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "🍏 This job's status is ${{ job.status }}."

