name: Build wheels

env:
  # A commit hash for the repo, for which to build wheels. 
  SOURCE_REF_TO_BUILD: ebfb3fa57d071c68402979810a6925219468466c

on: [push]

jobs:
  build_wheels:
    name: Build wheel ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          - [ubuntu-22.04, manylinux_x86_64, ""]

        python: ["cp312"]

    steps:
      - name: Checkout pyreadstat-wheels
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Checkout pyreadstat
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: Roche/pyreadstat
          ref: ${{ env.SOURCE_REF_TO_BUILD }}
          path: pyreadstat
          submodules: true
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@9c00cb4f6b517705a3794b22395aedc36257242c  # v3.2.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          SRC: ${{ github.workspace }}/pyreadstat
        with:
           package-dir: pyreadstat
           output-dir: dist
           config-file: cibuildwheel.toml

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
          path: ./dist/*.whl

      - name: Test Wheel
        run: |
          pip install -r requirements_test.txt
          ls dist
          pip install dist/*.whl 
          python pyreadstat/tests/test_basic.py

